In [84]:
import pandas as pd

path = "../luad_tcga_pan_can_atlas_2018/"

In [85]:
# ----------------------
# LOAD CLINICAL DATA
# ----------------------
clinical = pd.read_csv(path + "data_clinical_patient.txt", sep="\t", skiprows=4)

In [86]:
clinical.head()

,PATIENT_ID,SUBTYPE,CANCER_TYPE_ACRONYM,OTHER_PATIENT_ID,AGE,SEX,AJCC_PATHOLOGIC_TUMOR_STAGE,AJCC_STAGING_EDITION,DAYS_LAST_FOLLOWUP,DAYS_TO_BIRTH,...,IN_PANCANPATHWAYS_FREEZE,OS_STATUS,OS_MONTHS,DSS_STATUS,DSS_MONTHS,DFS_STATUS,DFS_MONTHS,PFS_STATUS,PFS_MONTHS,GENETIC_ANCESTRY_LABEL
0,TCGA-05-4244,LUAD,LUAD,34040b83-7e8a-4264-a551-b16621843e28,70.0,Male,STAGE IV,6TH,0.0,-25752.0,...,Yes,0:LIVING,0.000000,0:ALIVE OR DEAD TUMOR FREE,0.000000,NaN,NaN,0:CENSORED,0.000000,EUR
1,TCGA-05-4249,LUAD,LUAD,4addf05f-3668-4b3f-a17f-c0227329ca52,67.0,Male,STAGE IB,6TH,1523.0,-24532.0,...,Yes,0:LIVING,50.070684,0:ALIVE OR DEAD TUMOR FREE,50.070684,NaN,NaN,0:CENSORED,50.070684,EUR
2,TCGA-05-4250,LUAD,LUAD,f98ecd8a-b878-4f53-b911-20cd8e17281c,79.0,Female,STAGE IIIA,6TH,NaN,-29068.0,...,Yes,1:DECEASED,3.978039,NaN,3.978039,NaN,NaN,0:CENSORED,3.978039,EUR
3,TCGA-05-4382,LUAD,LUAD,3434b91a-c05f-460f-a078-7b1bb6e7085d,68.0,Male,STAGE IB,6TH,607.0,-24868.0,...,Yes,0:LIVING,19.955946,0:ALIVE OR DEAD TUMOR FREE,19.955946,1:Recurred/Progressed,10.980702,1:PROGRESSION,10.980702,EUR
4,TCGA-05-4384,LUAD,LUAD,9a50e7e4-831d-489f-87d2-979e987561cc,66.0,Male,STAGE IIIA,6TH,426.0,-24411.0,...,Yes,0:LIVING,14.005326,0:ALIVE OR DEAD TUMOR FREE,14.005326,NaN,NaN,1:PROGRESSION,6.016372,EUR

In [87]:
clinical.columns.tolist()

['PATIENT_ID',
 'SUBTYPE',
 'CANCER_TYPE_ACRONYM',
 'OTHER_PATIENT_ID',
 'AGE',
 'SEX',
 'AJCC_PATHOLOGIC_TUMOR_STAGE',
 'AJCC_STAGING_EDITION',
 'DAYS_LAST_FOLLOWUP',
 'DAYS_TO_BIRTH',
 'DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS',
 'ETHNICITY',
 'FORM_COMPLETION_DATE',
 'HISTORY_NEOADJUVANT_TRTYN',
 'ICD_10',
 'ICD_O_3_HISTOLOGY',
 'ICD_O_3_SITE',
 'INFORMED_CONSENT_VERIFIED',
 'NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT',
 'PATH_M_STAGE',
 'PATH_N_STAGE',
 'PATH_T_STAGE',
 'PERSON_NEOPLASM_CANCER_STATUS',
 'PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT',
 'PRIOR_DX',
 'RACE',
 'RADIATION_THERAPY',
 'WEIGHT',
 'IN_PANCANPATHWAYS_FREEZE',
 'OS_STATUS',
 'OS_MONTHS',
 'DSS_STATUS',
 'DSS_MONTHS',
 'DFS_STATUS',
 'DFS_MONTHS',
 'PFS_STATUS',
 'PFS_MONTHS',
 'GENETIC_ANCESTRY_LABEL']

In [88]:
print("Clinical loaded:", clinical.shape)
#print("PATIENT_ID unique values: ", clinical["PATIENT_ID"].unique())
print("SUBTYPE unique values: ", clinical['SUBTYPE'].unique())
print("CANCER_TYPE_ACRONYM unique values: ", clinical["CANCER_TYPE_ACRONYM"].unique())
#print("OTHER_PATIENT_ID unique values: ", clinical["OTHER_PATIENT_ID"].unique())
#print("AGE unique values: ", clinical["AGE"].unique())
#print("SEX unique values: ", clinical["SEX"].unique())
print("AJCC_PATHOLOGIC_TUMOR_STAGE unique values: ", clinical["AJCC_PATHOLOGIC_TUMOR_STAGE"].unique())
print("AJCC_STAGING_EDITION unique values: ", clinical["AJCC_STAGING_EDITION"].unique())
#print("DAYS_LAST_FOLLOWUP unique values: ", clinical["DAYS_LAST_FOLLOWUP"].unique())
#print("DAYS_TO_BIRTH unique values: ", clinical["DAYS_TO_BIRTH"].unique())
#print("DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS unique values: ", clinical["DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS"].unique())
print("ETHNICITY unique values: ", clinical["ETHNICITY"].unique())
#print("FORM_COMPLETION_DATE unique values: ", clinical["FORM_COMPLETION_DATE"].unique())
print("HISTORY_NEOADJUVANT_TRTYN unique values: ", clinical["HISTORY_NEOADJUVANT_TRTYN"].unique())
print("ICD_10 unique values: ", clinical["ICD_10"].unique())
print("ICD_O_3_HISTOLOGY unique values: ", clinical["ICD_O_3_HISTOLOGY"].unique())
print("ICD_O_3_SITE unique values: ", clinical["ICD_O_3_SITE"].unique())
#print("INFORMED_CONSENT_VERIFIED unique values: ", clinical["INFORMED_CONSENT_VERIFIED"].unique())
print("NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values: ", clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].unique())
print("PATH_M_STAGE unique values: ", clinical["PATH_M_STAGE"].unique())
print("PATH_N_STAGE unique values: ", clinical["PATH_N_STAGE"].unique())
print("PATH_T_STAGE unique values: ", clinical["PATH_T_STAGE"].unique())
print("PERSON_NEOPLASM_CANCER_STATUS unique values: ", clinical["PERSON_NEOPLASM_CANCER_STATUS"].unique())
print("PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT unique values: ", clinical["PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT"].unique())
print("PRIOR_DX unique values: ", clinical["PRIOR_DX"].unique())
#print("RACE unique values: ", clinical["RACE"].unique())
print("RADIATION_THERAPY unique values: ", clinical["RADIATION_THERAPY"].unique())
#print("WEIGHT unique values: ", clinical["WEIGHT"].unique())
#print("IN_PANCANPATHWAYS_FREEZE unique values: ", clinical["IN_PANCANPATHWAYS_FREEZE"].unique())
print("OS_STATUS unique values: ", clinical["OS_STATUS"].unique())
#print("OS_MONTHS unique values: ", clinical["OS_MONTHS"].unique())
print("DSS_STATUS unique values: ", clinical["DSS_STATUS"].unique())
#print("DSS_MONTHS unique values: ", clinical["DSS_MONTHS"].unique())
print("DFS_STATUS unique values: ", clinical["DFS_STATUS"].unique())
#print("DFS_MONTHS unique values: ", clinical["DFS_MONTHS"].unique())
print("PFS_STATUS unique values: ", clinical["PFS_STATUS"].unique())
#print("PFS_MONTHS unique values: ", clinical["PFS_MONTHS"].unique())
#print("GENETIC_ANCESTRY_LABEL unique values: ", clinical["GENETIC_ANCESTRY_LABEL"].unique())

Clinical loaded: (566, 38)
SUBTYPE unique values:  ['LUAD' nan]
CANCER_TYPE_ACRONYM unique values:  ['LUAD']
AJCC_PATHOLOGIC_TUMOR_STAGE unique values:  ['STAGE IV' 'STAGE IB' 'STAGE IIIA' 'STAGE IA' 'STAGE IIIB' 'STAGE IIB'
 'STAGE IIA' 'STAGE II' 'STAGE I' nan]
AJCC_STAGING_EDITION unique values:  ['6TH' '5TH' '7TH' nan '3RD' '4TH']
ETHNICITY unique values:  [nan 'Not Hispanic Or Latino' 'Hispanic Or Latino']
HISTORY_NEOADJUVANT_TRTYN unique values:  ['No' 'Yes' nan]
ICD_10 unique values:  ['C34.3' 'C34.1' 'C34.2' 'C34.9' 'C34.30' 'C34.0' 'C34.8' nan]
ICD_O_3_HISTOLOGY unique values:  ['8140/3' '8255/3' '8550/3' '8480/3' '8260/3' '8310/3' '8252/3' '8253/3'
 '8230/3' '8507/3' '8250/3' '8490/3' nan]
ICD_O_3_SITE unique values:  ['C34.3' 'C34.1' 'C34.2' 'C34.9' 'C34.0' 'C34.8' nan]
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values:  [nan 'No' 'Yes']
PATH_M_STAGE unique values:  ['M1' 'M0' nan 'MX' 'M1B' 'M1A']
PATH_N_STAGE unique values:  ['N2' 'N0' 'N1' 'N3' 'NX' nan]
PATH_T_STAGE unique values:  ['T2' 'T3' 'T1' 'T4' 'T2B' 'T1B' 'T2A' 'T1A' 'TX' nan]
PERSON_NEOPLASM_CANCER_STATUS unique values:  ['Tumor Free' nan 'With Tumor']
PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT unique values:  [nan]
PRIOR_DX unique values:  ['No' 'Yes' 'Yes, History Of Synchronous And Or Bilateral Malignancy' nan]
RADIATION_THERAPY unique values:  [nan 'No' 'Yes']
OS_STATUS unique values:  ['0:LIVING' '1:DECEASED' nan]
DSS_STATUS unique values:  ['0:ALIVE OR DEAD TUMOR FREE' nan '1:DEAD WITH TUMOR']
DFS_STATUS unique values:  [nan '1:Recurred/Progressed' '0:DiseaseFree']
PFS_STATUS unique values:  ['0:CENSORED' '1:PROGRESSION' nan]

In [89]:
print("Clinical loaded:", clinical.shape)
#print("PATIENT_ID unique values: ", clinical["PATIENT_ID"].unique())



#print("AGE unique values: ", clinical["AGE"].unique())
#print("SEX unique values: ", clinical["SEX"].unique())
print("AJCC_PATHOLOGIC_TUMOR_STAGE unique values: ", clinical["AJCC_PATHOLOGIC_TUMOR_STAGE"].unique())
print("AJCC_STAGING_EDITION unique values: ", clinical["AJCC_STAGING_EDITION"].unique())


#print("DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS unique values: ", clinical["DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS"].unique())


print("HISTORY_NEOADJUVANT_TRTYN unique values: ", clinical["HISTORY_NEOADJUVANT_TRTYN"].unique())
print("ICD_10 unique values: ", clinical["ICD_10"].unique())
print("ICD_O_3_HISTOLOGY unique values: ", clinical["ICD_O_3_HISTOLOGY"].unique())
print("ICD_O_3_SITE unique values: ", clinical["ICD_O_3_SITE"].unique())

print("NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values: ", clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].unique())
print("PATH_M_STAGE unique values: ", clinical["PATH_M_STAGE"].unique())
print("PATH_N_STAGE unique values: ", clinical["PATH_N_STAGE"].unique())
print("PATH_T_STAGE unique values: ", clinical["PATH_T_STAGE"].unique())
print("PERSON_NEOPLASM_CANCER_STATUS unique values: ", clinical["PERSON_NEOPLASM_CANCER_STATUS"].unique())
print("PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT unique values: ", clinical["PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT"].unique())
print("PRIOR_DX unique values: ", clinical["PRIOR_DX"].unique())

print("RADIATION_THERAPY unique values: ", clinical["RADIATION_THERAPY"].unique())
#print("WEIGHT unique values: ", clinical["WEIGHT"].unique())

print("OS_STATUS unique values: ", clinical["OS_STATUS"].unique())
#print("OS_MONTHS unique values: ", clinical["OS_MONTHS"].unique())


print("DFS_STATUS unique values: ", clinical["DFS_STATUS"].unique())
#print("DFS_MONTHS unique values: ", clinical["DFS_MONTHS"].unique())
print("PFS_STATUS unique values: ", clinical["PFS_STATUS"].unique())
#print("PFS_MONTHS unique values: ", clinical["PFS_MONTHS"].unique())

Clinical loaded: (566, 38)
AJCC_PATHOLOGIC_TUMOR_STAGE unique values:  ['STAGE IV' 'STAGE IB' 'STAGE IIIA' 'STAGE IA' 'STAGE IIIB' 'STAGE IIB'
 'STAGE IIA' 'STAGE II' 'STAGE I' nan]
AJCC_STAGING_EDITION unique values:  ['6TH' '5TH' '7TH' nan '3RD' '4TH']
HISTORY_NEOADJUVANT_TRTYN unique values:  ['No' 'Yes' nan]
ICD_10 unique values:  ['C34.3' 'C34.1' 'C34.2' 'C34.9' 'C34.30' 'C34.0' 'C34.8' nan]
ICD_O_3_HISTOLOGY unique values:  ['8140/3' '8255/3' '8550/3' '8480/3' '8260/3' '8310/3' '8252/3' '8253/3'
 '8230/3' '8507/3' '8250/3' '8490/3' nan]
ICD_O_3_SITE unique values:  ['C34.3' 'C34.1' 'C34.2' 'C34.9' 'C34.0' 'C34.8' nan]
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values:  [nan 'No' 'Yes']
PATH_M_STAGE unique values:  ['M1' 'M0' nan 'MX' 'M1B' 'M1A']
PATH_N_STAGE unique values:  ['N2' 'N0' 'N1' 'N3' 'NX' nan]
PATH_T_STAGE unique values:  ['T2' 'T3' 'T1' 'T4' 'T2B' 'T1B' 'T2A' 'T1A' 'TX' nan]
PERSON_NEOPLASM_CANCER_STATUS unique values:  ['Tumor Free' nan 'With Tumor']
PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT unique values:  [nan]
PRIOR_DX unique values:  ['No' 'Yes' 'Yes, History Of Synchronous And Or Bilateral Malignancy' nan]
RADIATION_THERAPY unique values:  [nan 'No' 'Yes']
OS_STATUS unique values:  ['0:LIVING' '1:DECEASED' nan]
DFS_STATUS unique values:  [nan '1:Recurred/Progressed' '0:DiseaseFree']
PFS_STATUS unique values:  ['0:CENSORED' '1:PROGRESSION' nan]

In [90]:
selected_columns = [
    "PATIENT_ID",
    "AJCC_PATHOLOGIC_TUMOR_STAGE",
    "AJCC_STAGING_EDITION",
    "HISTORY_NEOADJUVANT_TRTYN",
    "ICD_10",
    "ICD_O_3_HISTOLOGY",
    "ICD_O_3_SITE",
    "NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT",
    "PATH_M_STAGE",
    "PATH_N_STAGE",
    "PATH_T_STAGE",
    "PERSON_NEOPLASM_CANCER_STATUS",
    "PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT",
    "PRIOR_DX",
    "RADIATION_THERAPY",
    "OS_STATUS",
    "DFS_STATUS",
    "PFS_STATUS"
]

In [91]:
selected_clinical = clinical[selected_columns]

In [92]:
selected_clinical.head()

,PATIENT_ID,AJCC_PATHOLOGIC_TUMOR_STAGE,AJCC_STAGING_EDITION,HISTORY_NEOADJUVANT_TRTYN,ICD_10,ICD_O_3_HISTOLOGY,ICD_O_3_SITE,NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT,PATH_M_STAGE,PATH_N_STAGE,PATH_T_STAGE,PERSON_NEOPLASM_CANCER_STATUS,PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT,PRIOR_DX,RADIATION_THERAPY,OS_STATUS,DFS_STATUS,PFS_STATUS
0,TCGA-05-4244,STAGE IV,6TH,No,C34.3,8140/3,C34.3,NaN,M1,N2,T2,Tumor Free,NaN,No,NaN,0:LIVING,NaN,0:CENSORED
1,TCGA-05-4249,STAGE IB,6TH,No,C34.3,8140/3,C34.3,No,M0,N0,T2,Tumor Free,NaN,No,No,0:LIVING,NaN,0:CENSORED
2,TCGA-05-4250,STAGE IIIA,6TH,No,C34.3,8140/3,C34.3,NaN,M0,N1,T3,NaN,NaN,No,NaN,1:DECEASED,NaN,0:CENSORED
3,TCGA-05-4382,STAGE IB,6TH,No,C34.1,8255/3,C34.1,Yes,M0,N0,T2,Tumor Free,NaN,Yes,Yes,0:LIVING,1:Recurred/Progressed,1:PROGRESSION
4,TCGA-05-4384,STAGE IIIA,6TH,No,C34.3,8255/3,C34.3,Yes,M0,N2,T2,NaN,NaN,Yes,Yes,0:LIVING,NaN,1:PROGRESSION

In [93]:
selected_clinical.shape

(566, 18)

In [94]:
selected_clinical.isnull().sum()

PATIENT_ID                                      0
AJCC_PATHOLOGIC_TUMOR_STAGE                    54
AJCC_STAGING_EDITION                           73
HISTORY_NEOADJUVANT_TRTYN                      52
ICD_10                                         52
ICD_O_3_HISTOLOGY                              52
ICD_O_3_SITE                                   52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT       117
PATH_M_STAGE                                   56
PATH_N_STAGE                                   53
PATH_T_STAGE                                   52
PERSON_NEOPLASM_CANCER_STATUS                 145
PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT    566
PRIOR_DX                                       52
RADIATION_THERAPY                              99
OS_STATUS                                      52
DFS_STATUS                                    262
PFS_STATUS                                     52
dtype: int64

In [95]:
selected_clinical = selected_clinical.drop(columns=["PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT"])

In [96]:
selected_clinical.isnull().sum()

PATIENT_ID                                   0
AJCC_PATHOLOGIC_TUMOR_STAGE                 54
AJCC_STAGING_EDITION                        73
HISTORY_NEOADJUVANT_TRTYN                   52
ICD_10                                      52
ICD_O_3_HISTOLOGY                           52
ICD_O_3_SITE                                52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT    117
PATH_M_STAGE                                56
PATH_N_STAGE                                53
PATH_T_STAGE                                52
PERSON_NEOPLASM_CANCER_STATUS              145
PRIOR_DX                                    52
RADIATION_THERAPY                           99
OS_STATUS                                   52
DFS_STATUS                                 262
PFS_STATUS                                  52
dtype: int64

In [97]:
selected_clinical = selected_clinical.drop(columns=["DFS_STATUS"])

In [98]:
selected_clinical.isnull().sum()

PATIENT_ID                                   0
AJCC_PATHOLOGIC_TUMOR_STAGE                 54
AJCC_STAGING_EDITION                        73
HISTORY_NEOADJUVANT_TRTYN                   52
ICD_10                                      52
ICD_O_3_HISTOLOGY                           52
ICD_O_3_SITE                                52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT    117
PATH_M_STAGE                                56
PATH_N_STAGE                                53
PATH_T_STAGE                                52
PERSON_NEOPLASM_CANCER_STATUS              145
PRIOR_DX                                    52
RADIATION_THERAPY                           99
OS_STATUS                                   52
PFS_STATUS                                  52
dtype: int64

In [99]:
selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].mode()[0]

'No'

In [100]:
#NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values:  [nan 'No' 'Yes']
#fill the na values with mode
selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"] = selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].fillna(selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].mode()[0])

In [101]:
selected_clinical.isnull().sum()

PATIENT_ID                                   0
AJCC_PATHOLOGIC_TUMOR_STAGE                 54
AJCC_STAGING_EDITION                        73
HISTORY_NEOADJUVANT_TRTYN                   52
ICD_10                                      52
ICD_O_3_HISTOLOGY                           52
ICD_O_3_SITE                                52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT      0
PATH_M_STAGE                                56
PATH_N_STAGE                                53
PATH_T_STAGE                                52
PERSON_NEOPLASM_CANCER_STATUS              145
PRIOR_DX                                    52
RADIATION_THERAPY                           99
OS_STATUS                                   52
PFS_STATUS                                  52
dtype: int64

In [102]:
selected_clinical = selected_clinical.drop(columns=["AJCC_STAGING_EDITION","ICD_10","ICD_O_3_HISTOLOGY","ICD_O_3_SITE"])

In [103]:
selected_clinical.isnull().sum()

PATIENT_ID                                   0
AJCC_PATHOLOGIC_TUMOR_STAGE                 54
HISTORY_NEOADJUVANT_TRTYN                   52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT      0
PATH_M_STAGE                                56
PATH_N_STAGE                                53
PATH_T_STAGE                                52
PERSON_NEOPLASM_CANCER_STATUS              145
PRIOR_DX                                    52
RADIATION_THERAPY                           99
OS_STATUS                                   52
PFS_STATUS                                  52
dtype: int64

In [104]:
#drop PERSON_NEOPLASM_CANCER_STATUS column
selected_clinical = selected_clinical.drop(columns=["PERSON_NEOPLASM_CANCER_STATUS"])

In [105]:
selected_clinical.isnull().sum()

PATIENT_ID                                  0
AJCC_PATHOLOGIC_TUMOR_STAGE                54
HISTORY_NEOADJUVANT_TRTYN                  52
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT     0
PATH_M_STAGE                               56
PATH_N_STAGE                               53
PATH_T_STAGE                               52
PRIOR_DX                                   52
RADIATION_THERAPY                          99
OS_STATUS                                  52
PFS_STATUS                                 52
dtype: int64

In [106]:
selected_clinical.shape

(566, 11)

In [107]:
#remove rows with missing values
selected_clinical = selected_clinical.dropna()

In [108]:
selected_clinical.isnull().sum()

PATIENT_ID                                 0
AJCC_PATHOLOGIC_TUMOR_STAGE                0
HISTORY_NEOADJUVANT_TRTYN                  0
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT    0
PATH_M_STAGE                               0
PATH_N_STAGE                               0
PATH_T_STAGE                               0
PRIOR_DX                                   0
RADIATION_THERAPY                          0
OS_STATUS                                  0
PFS_STATUS                                 0
dtype: int64

In [109]:
selected_clinical.shape

(463, 11)

In [123]:
#unique values in each column
for column in selected_clinical.columns:
    print(f"{column} unique values: ", selected_clinical[column].unique())

PATIENT_ID unique values:  ['TCGA-05-4249' 'TCGA-05-4382' 'TCGA-05-4384' 'TCGA-05-4389'
 'TCGA-05-4390' 'TCGA-05-4398' 'TCGA-05-4402' 'TCGA-05-4405'
 'TCGA-05-4415' 'TCGA-05-4417' 'TCGA-05-4420' 'TCGA-05-4424'
 'TCGA-05-4427' 'TCGA-05-4432' 'TCGA-05-5425' 'TCGA-05-5428'
 'TCGA-38-4625' 'TCGA-38-4626' 'TCGA-38-4627' 'TCGA-38-4628'
 'TCGA-38-4631' 'TCGA-38-4632' 'TCGA-38-7271' 'TCGA-38-A44F'
 'TCGA-44-2655' 'TCGA-44-2656' 'TCGA-44-2657' 'TCGA-44-2659'
 'TCGA-44-2662' 'TCGA-44-2665' 'TCGA-44-2666' 'TCGA-44-2668'
 'TCGA-44-3396' 'TCGA-44-3398' 'TCGA-44-3917' 'TCGA-44-3918'
 'TCGA-44-3919' 'TCGA-44-4112' 'TCGA-44-5643' 'TCGA-44-6144'
 'TCGA-44-6145' 'TCGA-44-6146' 'TCGA-44-6148' 'TCGA-44-6774'
 'TCGA-44-6775' 'TCGA-44-6776' 'TCGA-44-6777' 'TCGA-44-6778'
 'TCGA-44-6779' 'TCGA-44-7659' 'TCGA-44-7660' 'TCGA-44-7661'
 'TCGA-44-7662' 'TCGA-44-7667' 'TCGA-44-7669' 'TCGA-44-7670'
 'TCGA-44-7671' 'TCGA-44-7672' 'TCGA-44-8117' 'TCGA-44-8119'
 'TCGA-44-8120' 'TCGA-44-A479' 'TCGA-44-A47A' 'TCGA-44-A47B'
 'TCGA-44-A47F' 'TCGA-44-A47G' 'TCGA-44-A4SS' 'TCGA-44-A4SU'
 'TCGA-49-4486' 'TCGA-49-4487' 'TCGA-49-4488' 'TCGA-49-4490'
 'TCGA-49-4501' 'TCGA-49-4505' 'TCGA-49-4506' 'TCGA-49-4507'
 'TCGA-49-4510' 'TCGA-49-4512' 'TCGA-49-4514' 'TCGA-49-6742'
 'TCGA-49-6743' 'TCGA-49-6744' 'TCGA-49-6745' 'TCGA-49-6761'
 'TCGA-49-AAQV' 'TCGA-49-AAR0' 'TCGA-49-AAR2' 'TCGA-49-AAR3'
 'TCGA-49-AAR4' 'TCGA-49-AAR9' 'TCGA-49-AARE' 'TCGA-49-AARN'
 'TCGA-49-AARO' 'TCGA-49-AARQ' 'TCGA-49-AARR' 'TCGA-4B-A93V'
 'TCGA-50-5044' 'TCGA-50-5045' 'TCGA-50-5049' 'TCGA-50-5051'
 'TCGA-50-5055' 'TCGA-50-5066' 'TCGA-50-5068' 'TCGA-50-5072'
 'TCGA-50-5930' 'TCGA-50-5931' 'TCGA-50-5932' 'TCGA-50-5933'
 'TCGA-50-5935' 'TCGA-50-5936' 'TCGA-50-5939' 'TCGA-50-5941'
 'TCGA-50-5942' 'TCGA-50-5944' 'TCGA-50-5946' 'TCGA-50-6590'
 'TCGA-50-6591' 'TCGA-50-6592' 'TCGA-50-6593' 'TCGA-50-6594'
 'TCGA-50-6595' 'TCGA-50-6597' 'TCGA-50-6673' 'TCGA-50-7109'
 'TCGA-50-8457' 'TCGA-50-8459' 'TCGA-50-8460' 'TCGA-53-7624'
 'TCGA-53-7626' 'TCGA-53-7813' 'TCGA-53-A4EZ' 'TCGA-55-1592'
 'TCGA-55-1595' 'TCGA-55-1596' 'TCGA-55-5899' 'TCGA-55-6543'
 'TCGA-55-6642' 'TCGA-55-6712' 'TCGA-55-6968' 'TCGA-55-6970'
 'TCGA-55-6971' 'TCGA-55-6972' 'TCGA-55-6975' 'TCGA-55-6978'
 'TCGA-55-6979' 'TCGA-55-6980' 'TCGA-55-6981' 'TCGA-55-6982'
 'TCGA-55-6983' 'TCGA-55-6984' 'TCGA-55-6985' 'TCGA-55-6986'
 'TCGA-55-6987' 'TCGA-55-7227' 'TCGA-55-7281' 'TCGA-55-7283'
 'TCGA-55-7284' 'TCGA-55-7570' 'TCGA-55-7573' 'TCGA-55-7574'
 'TCGA-55-7576' 'TCGA-55-7724' 'TCGA-55-7725' 'TCGA-55-7726'
 'TCGA-55-7727' 'TCGA-55-7728' 'TCGA-55-7815' 'TCGA-55-7816'
 'TCGA-55-7903' 'TCGA-55-7907' 'TCGA-55-7910' 'TCGA-55-7911'
 'TCGA-55-7913' 'TCGA-55-7914' 'TCGA-55-7994' 'TCGA-55-7995'
 'TCGA-55-8085' 'TCGA-55-8087' 'TCGA-55-8089' 'TCGA-55-8090'
 'TCGA-55-8091' 'TCGA-55-8092' 'TCGA-55-8094' 'TCGA-55-8096'
 'TCGA-55-8097' 'TCGA-55-8203' 'TCGA-55-8204' 'TCGA-55-8205'
 'TCGA-55-8206' 'TCGA-55-8207' 'TCGA-55-8208' 'TCGA-55-8299'
 'TCGA-55-8301' 'TCGA-55-8302' 'TCGA-55-8505' 'TCGA-55-8507'
 'TCGA-55-8508' 'TCGA-55-8510' 'TCGA-55-8511' 'TCGA-55-8512'
 'TCGA-55-8513' 'TCGA-55-8514' 'TCGA-55-8614' 'TCGA-55-8615'
 'TCGA-55-8619' 'TCGA-55-8620' 'TCGA-55-8621' 'TCGA-55-A48X'
 'TCGA-55-A48Y' 'TCGA-55-A48Z' 'TCGA-55-A490' 'TCGA-55-A491'
 'TCGA-55-A492' 'TCGA-55-A494' 'TCGA-55-A4DF' 'TCGA-55-A4DG'
 'TCGA-55-A57B' 'TCGA-62-8394' 'TCGA-62-8395' 'TCGA-62-8397'
 'TCGA-62-8398' 'TCGA-62-8399' 'TCGA-62-8402' 'TCGA-62-A46O'
 'TCGA-62-A46P' 'TCGA-62-A46R' 'TCGA-62-A46S' 'TCGA-62-A46U'
 'TCGA-62-A46V' 'TCGA-62-A46Y' 'TCGA-62-A470' 'TCGA-62-A471'
 'TCGA-62-A472' 'TCGA-64-1676' 'TCGA-64-1677' 'TCGA-64-1678'
 'TCGA-64-1679' 'TCGA-64-1680' 'TCGA-64-1681' 'TCGA-64-5774'
 'TCGA-64-5775' 'TCGA-64-5778' 'TCGA-64-5779' 'TCGA-64-5781'
 'TCGA-64-5815' 'TCGA-67-6215' 'TCGA-67-6216' 'TCGA-67-6217'
 'TCGA-69-7760' 'TCGA-69-7761' 'TCGA-69-7763' 'TCGA-69-7764'
 'TCGA-69-7765' 'TCGA-69-7973' 'TCGA-69-7974' 'TCGA-69-7978'
 'TCGA-69-7979' 'TCGA-69-7980' 'TCGA-69-8253' 'TCGA-69-8255'
 'TCGA-69-8453' 'TCGA-69-A59K' 'TCGA-71-6725' 'TCGA-71-8520'
 'TCGA-73-4658' 'TCGA-73-4659' 'TCGA-73-4662' 'TCGA-73-4666'
 'TCGA-73-4668' 'TCGA-73-4670' 'TCGA-73-4675' 'TCGA-73-4676'
 'TCGA-73-4677' 'TCGA-73-7498' 'TCGA-73-7499' 'TCGA-73-A9RS'
 'TCGA-75-5122' 'TCGA-75-5125' 'TCGA-75-5126' 'TCGA-75-5146'
 'TCGA-75-5147' 'TCGA-75-6203' 'TCGA-75-6205' 'TCGA-75-6206'
 'TCGA-75-6207' 'TCGA-75-6211' 'TCGA-75-6212' 'TCGA-75-6214'
 'TCGA-75-7025' 'TCGA-75-7027' 'TCGA-75-7030' 'TCGA-75-7031'
 'TCGA-78-7143' 'TCGA-78-7145' 'TCGA-78-7146' 'TCGA-78-7147'
 'TCGA-78-7148' 'TCGA-78-7149' 'TCGA-78-7150' 'TCGA-78-7152'
 'TCGA-78-7153' 'TCGA-78-7156' 'TCGA-78-7158' 'TCGA-78-7159'
 'TCGA-78-7160' 'TCGA-78-7161' 'TCGA-78-7162' 'TCGA-78-7163'
 'TCGA-78-7166' 'TCGA-78-7167' 'TCGA-78-7220' 'TCGA-78-7535'
 'TCGA-78-7536' 'TCGA-78-7537' 'TCGA-78-7539' 'TCGA-78-8640'
 'TCGA-78-8648' 'TCGA-78-8655' 'TCGA-78-8660' 'TCGA-78-8662'
 'TCGA-80-5607' 'TCGA-80-5608' 'TCGA-80-5611' 'TCGA-83-5908'
 'TCGA-86-6562' 'TCGA-86-6851' 'TCGA-86-7701' 'TCGA-86-7711'
 'TCGA-86-7713' 'TCGA-86-7714' 'TCGA-86-7953' 'TCGA-86-7954'
 'TCGA-86-7955' 'TCGA-86-8054' 'TCGA-86-8055' 'TCGA-86-8073'
 'TCGA-86-8075' 'TCGA-86-8076' 'TCGA-86-8278' 'TCGA-86-8279'
 'TCGA-86-8280' 'TCGA-86-8358' 'TCGA-86-8585' 'TCGA-86-8668'
 'TCGA-86-8669' 'TCGA-86-8671' 'TCGA-86-8672' 'TCGA-86-8673'
 'TCGA-86-8674' 'TCGA-86-A456' 'TCGA-86-A4D0' 'TCGA-86-A4JF'
 'TCGA-86-A4P7' 'TCGA-86-A4P8' 'TCGA-91-6828' 'TCGA-91-6829'
 'TCGA-91-6830' 'TCGA-91-6831' 'TCGA-91-6835' 'TCGA-91-6836'
 'TCGA-91-6840' 'TCGA-91-6847' 'TCGA-91-6848' 'TCGA-91-7771'
 'TCGA-91-8496' 'TCGA-91-8497' 'TCGA-91-8499' 'TCGA-91-A4BD'
 'TCGA-93-7347' 'TCGA-93-7348' 'TCGA-93-8067' 'TCGA-93-A4JN'
 'TCGA-93-A4JO' 'TCGA-93-A4JP' 'TCGA-93-A4JQ' 'TCGA-95-7039'
 'TCGA-95-7562' 'TCGA-95-7567' 'TCGA-95-7944' 'TCGA-95-7947'
 'TCGA-95-7948' 'TCGA-95-8039' 'TCGA-95-8494' 'TCGA-95-A4VK'
 'TCGA-95-A4VN' 'TCGA-95-A4VP' 'TCGA-97-7546' 'TCGA-97-7547'
 'TCGA-97-7552' 'TCGA-97-7553' 'TCGA-97-7554' 'TCGA-97-7937'
 'TCGA-97-7938' 'TCGA-97-7941' 'TCGA-97-8171' 'TCGA-97-8172'
 'TCGA-97-8174' 'TCGA-97-8175' 'TCGA-97-8176' 'TCGA-97-8177'
 'TCGA-97-8179' 'TCGA-97-8547' 'TCGA-97-8552' 'TCGA-97-A4LX'
 'TCGA-97-A4M0' 'TCGA-97-A4M1' 'TCGA-97-A4M2' 'TCGA-97-A4M3'
 'TCGA-97-A4M5' 'TCGA-97-A4M6' 'TCGA-97-A4M7' 'TCGA-99-7458'
 'TCGA-99-8025' 'TCGA-99-8028' 'TCGA-99-8032' 'TCGA-99-8033'
 'TCGA-99-AA5R' 'TCGA-J2-8192' 'TCGA-J2-8194' 'TCGA-J2-A4AD'
 'TCGA-J2-A4AE' 'TCGA-J2-A4AG' 'TCGA-L4-A4E5' 'TCGA-L4-A4E6'
 'TCGA-L9-A443' 'TCGA-L9-A444' 'TCGA-L9-A50W' 'TCGA-L9-A5IP'
 'TCGA-L9-A743' 'TCGA-L9-A7SV' 'TCGA-L9-A8F4' 'TCGA-MN-A4N1'
 'TCGA-MN-A4N4' 'TCGA-MN-A4N5' 'TCGA-MP-A4SV' 'TCGA-MP-A4SW'
 'TCGA-MP-A4SY' 'TCGA-MP-A4T2' 'TCGA-MP-A4T4' 'TCGA-MP-A4T6'
 'TCGA-MP-A4T7' 'TCGA-MP-A4T8' 'TCGA-MP-A4T9' 'TCGA-MP-A4TA'
 'TCGA-MP-A4TC' 'TCGA-MP-A4TD' 'TCGA-MP-A4TE' 'TCGA-MP-A4TF'
 'TCGA-MP-A4TH' 'TCGA-MP-A4TJ' 'TCGA-MP-A4TK' 'TCGA-MP-A5C7'
 'TCGA-NJ-A4YF' 'TCGA-NJ-A4YG' 'TCGA-NJ-A4YI' 'TCGA-NJ-A4YP'
 'TCGA-NJ-A4YQ' 'TCGA-NJ-A55A' 'TCGA-NJ-A55O' 'TCGA-NJ-A55R'
 'TCGA-NJ-A7XG' 'TCGA-O1-A52J' 'TCGA-S2-AA1A']
AJCC_PATHOLOGIC_TUMOR_STAGE unique values:  [1.2 3.1 1.1 3.2 4.  2.2 2.1 2.  1. ]
HISTORY_NEOADJUVANT_TRTYN unique values:  [0 1]
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT unique values:  [0 1]
PATH_M_STAGE unique values:  [ 0.   1.  -1.   1.2  1.1]
PATH_N_STAGE unique values:  [ 0  2  3 -1  1]
PATH_T_STAGE unique values:  [ 2.   1.   4.   3.   2.2  1.2  2.1  1.1 -1. ]
PRIOR_DX unique values:  [0 1]
RADIATION_THERAPY unique values:  [0 1]
OS_STATUS unique values:  [0 1]
PFS_STATUS unique values:  [0 1]

Now we have all the data cleaned.

Need to check further for the skewness.

In [111]:
#convert HISTORY_NEOADJUVANT_TRTYN to binary
selected_clinical["HISTORY_NEOADJUVANT_TRTYN"] = selected_clinical["HISTORY_NEOADJUVANT_TRTYN"].map({"Yes": 1, "No": 0})

In [112]:
#convert NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT, RADIATION_THERAPY  to binary
selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"] = selected_clinical["NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT"].map({"Yes": 1, "No": 0})
selected_clinical["RADIATION_THERAPY"] = selected_clinical["RADIATION_THERAPY"].map({"Yes": 1, "No": 0})

In [115]:
#convert 0:LIVING, 1:DECEASED to 0 and 1
selected_clinical["OS_STATUS"] = selected_clinical["OS_STATUS"].map({"0:LIVING": 0, "1:DECEASED": 1})

In [113]:
#convert 0:CENSORED, 1:DECEASED to 0 and 1
selected_clinical["PFS_STATUS"] = selected_clinical["PFS_STATUS"].map({"0:CENSORED": 0, "1:PROGRESSION": 1})

In [117]:
#Convert PRIOR_DX to binary
selected_clinical["PRIOR_DX"] = selected_clinical["PRIOR_DX"].map({"No": 0, "Yes": 1, "Yes, History Of Synchronous And Or Bilateral Malignancy": 1})

In [122]:
selected_clinical["AJCC_PATHOLOGIC_TUMOR_STAGE"] = selected_clinical["AJCC_PATHOLOGIC_TUMOR_STAGE"].map(
{
 'STAGE I':1.0,
 'STAGE IA':1.1,
 'STAGE IB':1.2,
 'STAGE II':2.0,
 'STAGE IIA':2.1,
 'STAGE IIB':2.2,
 'STAGE IIIA':3.1,
 'STAGE IIIB':3.2,
'STAGE IV':4.0
})

selected_clinical["PATH_T_STAGE"] = selected_clinical["PATH_T_STAGE"].map(
{
 'T1':1.0,
 'T1A':1.1,
 'T1B':1.2,
 'T2':2.0,
 'T2A':2.1,
 'T2B':2.2,
 'T3':3.0,
 'T4':4.0,
 'TX':-1
})

selected_clinical["PATH_N_STAGE"] = selected_clinical["PATH_N_STAGE"].map(
{
 'N0':0,
 'N1':1,
 'N2':2,
 'N3':3,
 'NX':-1
})

selected_clinical["PATH_M_STAGE"] = selected_clinical["PATH_M_STAGE"].map(
{
 'M0':0,
 'M1':1,
 'M1A':1.1,
 'M1B':1.2,
 'MX':-1
})

In [124]:
print(selected_clinical.info())
print(selected_clinical.describe())
print(selected_clinical.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 463 entries, 1 to 513
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   PATIENT_ID                               463 non-null    object
 1   AJCC_PATHOLOGIC_TUMOR_STAGE              463 non-null    float64
 2   HISTORY_NEOADJUVANT_TRTYN                463 non-null    int64
 3   NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT  463 non-null    int64
 4   PATH_M_STAGE                             463 non-null    float64
 5   PATH_N_STAGE                             463 non-null    int64
 6   PATH_T_STAGE                             463 non-null    float64
 7   PRIOR_DX                                 463 non-null    int64
 8   RADIATION_THERAPY                        463 non-null    int64
 9   OS_STATUS                                463 non-null    int64
 10  PFS_STATUS                               463 non-null    int64
dtypes: float64(3), int64(7), object(1)
memory usage: 43.4+ KB
None
       AJCC_PATHOLOGIC_TUMOR_STAGE  HISTORY_NEOADJUVANT_TRTYN  \
count                   463.000000                 463.000000
mean                      1.846436                   0.006479
std                       0.882357                   0.080321
min                       1.000000                   0.000000
25%                       1.100000                   0.000000
50%                       1.200000                   0.000000
75%                       2.200000                   0.000000
max                       4.000000                   1.000000

       NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT  PATH_M_STAGE  PATH_N_STAGE  \
count                               463.000000    463.000000    463.000000
mean                                  0.367171     -0.241469      0.457883
std                                   0.482555      0.535784      0.760110
min                                   0.000000     -1.000000     -1.000000
25%                                   0.000000     -1.000000      0.000000
50%                                   0.000000      0.000000      0.000000
75%                                   1.000000      0.000000      1.000000
max                                   1.000000      1.200000      3.000000

       PATH_T_STAGE    PRIOR_DX  RADIATION_THERAPY   OS_STATUS  PFS_STATUS
count    463.000000  463.000000         463.000000  463.000000  463.000000
mean       1.838013    0.170626           0.131749    0.367171    0.436285
std        0.730609    0.376589           0.338584    0.482555    0.496460
min       -1.000000    0.000000           0.000000    0.000000    0.000000
25%        1.200000    0.000000           0.000000    0.000000    0.000000
50%        2.000000    0.000000           0.000000    0.000000    0.000000
75%        2.100000    0.000000           0.000000    1.000000    1.000000
max        4.000000    1.000000           1.000000    1.000000    1.000000
PATIENT_ID                                 0
AJCC_PATHOLOGIC_TUMOR_STAGE                0
HISTORY_NEOADJUVANT_TRTYN                  0
NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT    0
PATH_M_STAGE                               0
PATH_N_STAGE                               0
PATH_T_STAGE                               0
PRIOR_DX                                   0
RADIATION_THERAPY                          0
OS_STATUS                                  0
PFS_STATUS                                 0
dtype: int64

In [ ]:
data_floder = "../Data/processed_data"

In [ ]:
#save the selected_clinical dataframe to a csv file
selected_clinical.to_csv(data_floder + "selected_clinical.csv", index=False)

In [127]:
selected_clinical.columns

Index(['PATIENT_ID', 'AJCC_PATHOLOGIC_TUMOR_STAGE',
       'HISTORY_NEOADJUVANT_TRTYN', 'NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT',
       'PATH_M_STAGE', 'PATH_N_STAGE', 'PATH_T_STAGE', 'PRIOR_DX',
       'RADIATION_THERAPY', 'OS_STATUS', 'PFS_STATUS'],
      dtype='object')